export default {
  login: "jasmeets-6575",
  id: 111236747,
  node_id: "U_kgDOBqFWiw",
  avatar_url: "https://avatars.githubusercontent.com/u/111236747?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jasmeets-6575",
  html_url: "https://github.com/jasmeets-6575",
  followers_url: "https://api.github.com/users/jasmeets-6575/followers",
  following_url:
    "https://api.github.com/users/jasmeets-6575/following{/other_user}",
  gists_url: "https://api.github.com/users/jasmeets-6575/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/jasmeets-6575/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jasmeets-6575/subscriptions",
  organizations_url: "https://api.github.com/users/jasmeets-6575/orgs",
  repos_url: "https://api.github.com/users/jasmeets-6575/repos",
  events_url: "https://api.github.com/users/jasmeets-6575/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/jasmeets-6575/received_events",
  type: "User",
  site_admin: false,
  name: "Jasmeet Singh",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Comprehension over configuration",
  twitter_username: null,
  public_repos: 18,
  public_gists: 0,
  followers: 20,
  following: 2,
  created_at: "2022-08-14T14:56:04Z",
  updated_at: "2023-01-12T10:44:20Z",
};
